name: Snyk container Scan

on:
  workflow_dispatch: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Install Snyk
        run: |
          npm install snyk -g 
          snyk -v
          snyk auth ${{ secrets.snyk_token }} # snyk authentication using GH secrets

        # Generate the HTML report
      - name: Run snyk test and install snyk-to-html
        run: | 
         echo "Install snyk-to-html package to convert the json scan outputs to html format"
         npm install snyk-to-html -g
         echo "Run snyk scan"
         snyk container test debian --json | snyk-to-html -o result.html
         snyk container test vulnerables/web-dvwa --json | snyk-to-html -o result-dvwa.html
         mkdir downloads
         pwd
         cp -v result.html /home/runner/work/*/*/downloads
         cp -v result-dvwa.html /home/runner/work/*/*/downloads
         snyk container monitor debian
         snyk container monitor vulnerables/web-dvwa
         
      # save the HTML in the artifact
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: results
          #path: /home/runner/*/*/*/*.json
          path: downloads
